steps:
  # Print the contents of the source directory to debug
  - name: 'gcr.io/cloud-builders/bash'
    args: ['-c', 'find /workspace -type f -name "*.h5" | xargs ls -la || echo "No model files found"']
  
  # Build the container image using Cloud Build's own container building capability
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/apple-harvest-app:$SHORT_SHA', '--platform', 'linux/amd64', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/apple-harvest-app:$SHORT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'apple-harvest-app'
    - '--image'
    - 'gcr.io/$PROJECT_ID/apple-harvest-app:$SHORT_SHA'
    - '--platform'
    - 'managed'
    - '--region'
    - '$_REGION'
    - '--allow-unauthenticated'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--timeout'
    - '300s'
    - '--set-env-vars'
    - 'GOOGLE_APPLICATION_CREDENTIALS=/etc/google/auth/credentials.json,BUCKET_NAME=$_BUCKET_NAME'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/apple-harvest-app:$SHORT_SHA'

substitutions:
  _REGION: us-central1
  _BUCKET_NAME: apple-454418-detection-images

options:
  logging: CLOUD_LOGGING_ONLY
  # Increase the timeout to handle large file uploads
  machineType: 'N1_HIGHCPU_8' 